// let words = [
//     "about",
//     "above",
//     "abuse",
//     "actor",
//     "acute",
//     "admit",
//     "adopt",
//     "adult",
//     "after",
//     "again",
//     "agent",
//     "agree",
//     "ahead",
//     "alarm",
//     "album",
//     "alert",
//     "alike",
//     "alive",
//     "allow",
//     "alone",
//     "along",
//     "alter",
//     "among",
//     "anger",
//     "Angle",
//     "angry",
//     "apart",
//     "apple",
//     "apply",
//     "arena",
//     "argue",
//     "arise",
//     "array",
//     "aside",
//     "asset",
//     "audio",
//     "audit",
//     "avoid",
//     "award",
//     "aware",
//     "badly",
//     "baker",
//     "bases",
//     "basic",
//     "basis",
//     "beach",
//     "began",
//     "begin",
//     "begun",
//     "being",
//     "below",
//     "bench",
//     "billy",
//     "birth",
//     "black",
//     "blame",
//     "blind",
//     "block",
//     "blood",
//     "board",
//     "boost",
//     "booth",
//     "bound",
//     "brain",
//     "brand",
//     "bread",
//     "break",
//     "breed",
//     "brief",
//     "bring",
//     "broad",
//     "broke",
//     "brown",
//     "build",
//     "built",
//     "buyer",
//     "cable",
//     "calif",
//     "carry",
//     "catch",
//     "cause",
//     "chain",
//     "chair",
//     "chart",
//     "chase",
//     "cheap",
//     "check",
//     "chest",
//     "chief",
//     "child",
//     "china",
//     "chose",
//     "civil",
//     "claim",
//     "class",
//     "clean",
//     "clear",
//     "click",
//     "clock",
//     "close",
//     "coach",
//     "coast",
//     "could",
//     "count",
//     "court",
//     "cover",
//     "craft",
//     "crash",
//     "cream",
//     "crime",
//     "cross",
//     "crowd",
//     "crown",
//     "curve",
//     "cycle",
//     "daily",
//     "dance",
//     "dated",
//     "dealt",
//     "death",
//     "debut",
//     "delay",
//     "depth",
//     "doing",
//     "doubt",
//     "dozen",
//     "draft",
//     "drama",
//     "drawn",
//     "dream",
//     "dress",
//     "drill",
//     "drink",
//     "drive",
//     "drove",
//     "dying",
//     "eager",
//     "early",
//     "earth",
//     "eight",
//     "elite",
//     "empty",
//     "enemy",
//     "enjoy",
//     "enter",
//     "entry",
//     "equal",
//     "error",
//     "event",
//     "every",
//     "exact",
//     "exist",
//     "extra",
//     "faith",
//     "false",
//     "fault",
//     "fiber",
//     "field",
//     "fifth",
//     "fifty",
//     "fight",
//     "final",
//     "first",
//     "fixed",
//     "flash",
//     "fleet",
//     "floor",
//     "fluid",
//     "focus",
//     "force",
//     "forth",
//     "forty",
//     "forum",
//     "found",
//     "frame",
//     "frank",
//     "fraud",
//     "fresh",
//     "front",
//     "fruit",
//     "fully",
//     "funny",
//     "giant",
//     "given",
//     "glass",
//     "globe",
//     "going",
//     "grace",
//     "grade",
//     "grand",
//     "grant",
//     "grass",
//     "great",
//     "green",
//     "gross",
//     "group",
//     "grown",
//     "guard",
//     "guess",
//     "guest",
//     "guide",
//     "happy",
//     "heart",
//     "heavy",
//     "hence",
//     "horse",
//     "hotel",
//     "house",
//     "human",
//     "ideal",
//     "image",
//     "index",
//     "inner",
//     "input",
//     "issue",
//     "japan",
//     "joint",
//     "jones",
//     "judge",
//     "known",
//     "label",
//     "large",
//     "laser",
//     "later",
//     "laugh",
//     "layer",
//     "learn",
//     "lease",
//     "least",
//     "leave",
//     "legal",
//     "level",
//     "lewis",
//     "light",
//     "limit",
//     "links",
//     "lives",
//     "local",
//     "logic",
//     "loose",
//     "lower",
//     "lucky",
//     "lunch",
//     "lying",
//     "magic",
//     "major",
//     "maker",
//     "march",
//     "maria",
//     "match",
//     "maybe",
//     "mayor",
//     "meant",
//     "media",
//     "metal",
//     "might",
//     "minor",
//     "minus",
//     "mixed",
//     "model",
//     "money",
//     "month",
//     "moral",
//     "motor",
//     "mount",
//     "mouse",
//     "mouth",
//     "movie",
//     "music",
//     "needs",
//     "never",
//     "newly",
//     "night",
//     "noise",
//     "north",
//     "noted",
//     "novel",
//     "nurse",
//     "occur",
//     "ocean",
//     "offer",
//     "often",
//     "order",
//     "other",
//     "ought",
//     "paint",
//     "panel",
//     "paper",
//     "party",
//     "peace",
//     "peter",
//     "phase",
//     "phone",
//     "photo",
//     "piece",
//     "pilot",
//     "pitch",
//     "place",
//     "plain",
//     "plane",
//     "plant",
//     "plate",
//     "point",
//     "pound",
//     "power",
//     "press",
//     "price",
//     "pride",
//     "prime",
//     "print",
//     "prior",
//     "prize",
//     "proof",
//     "proud",
//     "prove",
//     "queen",
//     "quick",
//     "quiet",
//     "quite",
//     "radio",
//     "raise",
//     "range",
//     "rapid",
//     "ratio",
//     "reach",
//     "ready",
//     "refer",
//     "right",
//     "rival",
//     "river",
//     "robin",
//     "roger",
//     "roman",
//     "rough",
//     "round",
//     "route",
//     "royal",
//     "rural",
//     "scale",
//     "scene",
//     "scope",
//     "score",
//     "sense",
//     "serve",
//     "seven",
//     "shall",
//     "shape",
//     "share",
//     "sharp",
//     "sheet",
//     "shelf",
//     "shell",
//     "shift",
//     "shirt",
//     "shock",
//     "shoot",
//     "short",
//     "shown",
//     "sight",
//     "since",
//     "sixth",
//     "sixty",
//     "sized",
//     "skill",
//     "sleep",
//     "slide",
//     "small",
//     "smart",
//     "smile",
//     "smith",
//     "smoke",
//     "solid",
//     "solve",
//     "sorry",
//     "sound",
//     "south",
//     "space",
//     "spare",
//     "speak",
//     "speed",
//     "spend",
//     "spent",
//     "split",
//     "spoke",
//     "sport",
//     "staff",
//     "stage",
//     "stake",
//     "stand",
//     "start",
//     "state",
//     "steam",
//     "steel",
//     "stick",
//     "still",
//     "stock",
//     "stone",
//     "stood",
//     "store",
//     "storm",
//     "story",
//     "strip",
//     "stuck",
//     "study",
//     "stuff",
//     "style",
//     "sugar",
//     "suite",
//     "super",
//     "sweet",
//     "table",
//     "taken",
//     "taste",
//     "taxes",
//     "teach",
//     "teeth",
//     "terry",
//     "texas",
//     "thank",
//     "theft",
//     "their",
//     "theme",
//     "there",
//     "these",
//     "thick",
//     "thing",
//     "think",
//     "third",
//     "those",
//     "three",
//     "threw",
//     "throw",
//     "tight",
//     "times",
//     "tired",
//     "title",
//     "today",
//     "topic",
//     "total",
//     "touch",
//     "tough",
//     "tower",
//     "track",
//     "trade",
//     "train",
//     "treat",
//     "trend",
//     "trial",
//     "tried",
//     "tries",
//     "truck",
//     "truly",
//     "trust",
//     "truth",
//     "twice",
//     "under",
//     "undue",
//     "union",
//     "unity",
//     "until",
//     "upper",
//     "upset",
//     "urban",
//     "usage",
//     "usual",
//     "valid",
//     "value",
//     "video",
//     "virus",
//     "visit",
//     "vital",
//     "voice",
//     "waste",
//     "watch",
//     "water",
//     "wheel",
//     "where",
//     "which",
//     "while",
//     "white",
//     "whole",
//     "whose",
//     "woman",
//     "women",
//     "world",
//     "worry",
//     "worse",
//     "worst",
//     "worth",
//     "would",
//     "wound",
//     "write",
//     "wrong",
//     "wrote",
//     "yield",
//     "young",
//     "youth"
// ]

// let mathwords = [
//     "angle",
//     "carry",
//     "curve",
//     "eight",
//     "equal",
//     "fifty",
//     "forty",
//     "graph",
//     "minus",
//     "point",
//     "prime",
//     "proof",
//     "seven",
//     "sixty",
//     "slope",
//     "solve",
//     "tenth",
//     "three",
//     "times",
//     "torus",
//     "union",
//     "whole"
// ]

// let computerwords = [
//     "Abort",
//     "Algol",
//     "Apple",
//     "Arial",
//     "Ascii",
//     "Basic",
//     "Block",
//     "Board",
//     "Cache",
//     "Click",
//     "Close",
//     "Cobol",
//     "Coral",
//     "Crash",
//     "Debug",
//     "Email",
//     "Eprom",
//     "Erase",
//     "Excel",
//     "Flash",
//     "Forth",
//     "Forum",
//     "Frame",
//     "Gates",
//     "Image",
//     "Input",
//     "Intel",
//     "Laser",
//     "Layer",
//     "Logic",
//     "Login",
//     "Logon",
//     "Macro",
//     "Media",
//     "Micro",
//     "Modem",
//     "Morph",
//     "Mouse",
//     "Octal",
//     "Paint",
//     "Panel",
//     "Patch",
//     "Pixel",
//     "Proxy",
//     "Purge",
//     "Query",
//     "Queue",
//     "Reset",
//     "Robot",
//     "Spool",
//     "Stack",
//     "Stats",
//     "Suite",
//     "Table",
//     "Track",
//     "Tweet",
//     "Virus",
//     "Write"
// ]

// let sciencewords = [
//     "Adams",
//     "Aiken",
//     "Amici",
//     "Aston",
//     "Bacon",
//     "Baily",
//     "Baird",
//     "Banks",
//     "Baumé",
//     "Black",
//     "Bloch",
//     "Boole",
//     "Booth",
//     "Bosch",
//     "Bothe",
//     "Boyle",
//     "Bragg",
//     "Brahe",
//     "Brown",
//     "Carré",
//     "Chain",
//     "Cooke",
//     "Crick",
//     "Curie",
//     "Dalen",
//     "Debye",
//     "Dewar",
//     "Dirac",
//     "Dyson",
//     "Encke",
//     "Euler",
//     "Fermi",
//     "Frank",
//     "Frege",
//     "Gabor",
//     "Galle",
//     "Gauss",
//     "Gibbs",
//     "Godel",
//     "Haber",
//     "Hardy",
//     "Henry",
//     "Hertz",
//     "Hooke",
//     "Hoyle",
//     "Hyatt",
//     "Jeans",
//     "Joule",
//     "Klein",
//     "Kowal",
//     "Krebs",
//     "Libby",
//     "Lodge",
//     "Magee",
//     "Maxim",
//     "Mayer",
//     "Monge",
//     "Moore",
//     "Morse",
//     "Nobel",
//     "Noble",
//     "Papin",
//     "Pasch",
//     "Pauli",
//     "Raman",
//     "Reber",
//     "Ritty",
//     "Romer",
//     "Rosse",
//     "Sagan",
//     "Segre",
//     "Short",
//     "Smith",
//     "Soddy",
//     "Stahl",
//     "Tatum",
//     "Tesla",
//     "Volta",
//     "Weber",
//     "White",
//     "Young"
// ]



let words = [
    {
        "word": "about",
        "clue1": "This word is a preposition",
        "clue2": "This word means the subject of",
        "clue3": "I was very concerned _____ you after you fell down and broke your arm"

    },
    {
        "word": "above",
        "clue1": "This word can be used as a preposition or adverb ",
        "clue2": "This word is used to indicate what is higer than you",
        "clue3": "The bird flew high _____ me"

    },
    {
        "word": "abuse",
        "clue1": "This word is a verb.",
        "clue2": "This word means that you misues something or you take advantage of it",
        "clue3": "Sometimes people ______ there power"

    },
    {
        "word": "actor",
        "clue1": "This word is a noun.",
        "clue2": "To behave in a way that is not usual to you",
        "clue3": "Will Smith is the one of the greatst _____ in Hollywood"

    },
    {
        "word": "acute",
        "clue1": "This word is related to math.",
        "clue2": "This word can be used to descibe shapes",
        "clue3": "_____ angles are always less than 90°"

    },
    {
        "word": "admit",
        "clue1": "This word is related to hospitals",
        "clue2": "A synonym for this word is confess",
        "clue3": "I was _____ed into the hopsital"

    },
    {
        "word": "adopt",
        "clue1": "This word means to bring into the family",
        "clue2": "This word is related to orphanage",
        "clue3": "My family _____ed a child from a orphanage"

    },
    {
        "word": "adult",
        "clue1": "This word is someone who is fully matured",
        "clue2": "This word is the oppiste of kid",
        "clue3": "You have to be 18 to be an _____"

    },
    {
        "word": "after",
        "clue1": "This word means at a later time",
        "clue2": "This word is the opposite of before",
        "clue3": "I will compleate my homework _____ some time"

    },
    {
        "word": "again",
        "clue1": "This word is a adverb",
        "clue2": "This word means to repeat",
        "clue3": "My homework got ruined so I hvae to do it _____"

    },
    {
        "word": "agent",
        "clue1": "This word is a noun",
        "clue2": "This word is relateted to spys",
        "clue3": "Spys or _____s have to be smart and cunning"

    },
    {
        "word": "agree",
        "clue1": "This word is a verb",
        "clue2": "This word means to come to a comprise",
        "clue3": "We had to _____ on what theme was best for the slideshow"

    },
    {
        "word": "ahead",
        "clue1": "",
        "clue2": "This word means something thats in front of you",
        "clue3": "We had to _____ on what theme was best for the slideshow"

    },
    {
        "word": "horse",
        "clue1": "It's a land mammal.",
        "clue2": "It has four legs, a tail and is 4.82 feet tall.",
        "clue3": "Me and my brother love to go _____back riding."

    },
    {
        "word": "crane",
        "clue1": "It's a bird.",
        "clue2": "It has two legs and a long neck.",
        "clue3": "In Japan the _____ is considered a holy bird."

    },
    {
        "word": "brick",
        "clue1": "Red in color and is rough",
        "clue2": "It is not living and is in a rectangular shape.",
        "clue3": "People commonly think that _____ is used to build houses."

    },
    {
        "word": "young",
        "clue1": "It's an adjective.",
        "clue2": "It's usually used to describe kids",
        "clue3": "Kids are _____ than adults"

    }
]
    // Angry: one of your emotins - 10
    // Angry: It's an unproductive emotion too have - 20
    // Angry: """"I was _____ at my brother for walking into my room.""""- 50
    //     "ahead",
    //     "alarm",
    //     "album",
    //     "alert",
    //     "alike",
    //     "alive",
    //     "allow",
    //     "alone",
    //     "along",
    //     "alter",
    //     "among",
    //     "anger",
    //     "Angle",
    //     "angry",
    //     "apart",
    //     "apple",
    //     "apply",
    //     "arena",
    //     "argue",
    //     "arise",
    //     "array",
    //     "aside",
    //     "asset",
    //     "audio",
    //     "audit",
    //     "avoid",
    //     "award",
    //     "aware",